'use client';

import { Feedback } from "@/types/feedback";
import SentimentBadge from "./sentiment-badge";

interface FeedbackDetailPanelProps {
  feedback: Feedback;
  onClose: () => void;
}

export default function FeedbackDetailPanel({
  feedback,
  onClose,
}: FeedbackDetailPanelProps) {

  const getInitials = (name: string) =>
    name
      .split(" ")
      .map((part) => part[0])
      .join("");

  const renderResponse = (
    answer: string | number | string[]
  ) => {
    if (Array.isArray(answer)) {
      return (
        <div className="flex flex-wrap gap-2 mt-2">
          {answer.map((item) => (
            <span
              key={item}
              className="px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-xs font-medium"
            >
              {item}
            </span>
          ))}
        </div>
      );
    }

    return (
      <p className="mt-2 text-gray-900">
        {answer}
      </p>
    );
  };

  const MetricCard = ({
    title,
    value,
    icon,
  }: {
    title: string;
    value: string;
    icon: string;
  }) => (
    <div className="rounded-xl border border-gray-200 bg-gray-50 p-4">
      <p className="text-xs text-gray-500 mb-2">
        {icon} {title}
      </p>

      <p className="text-lg font-semibold text-gray-900">
        {value}
      </p>
    </div>
  );

  const FeatureChip = ({
    value,
    positive = true,
  }: {
    value: string;
    positive?: boolean;
  }) => (
    <span
      className={`px-3 py-1 rounded-full text-sm font-medium ${positive
          ? "bg-green-50 text-green-700"
          : "bg-red-50 text-red-700"
        }`}
    >
      {value}
    </span>
  );

  return (
    <div
      className="
      w-full
      xl:w-[430px]
      bg-white
      border
      border-gray-200
      rounded-2xl
      shadow-lg
      overflow-y-auto
      max-h-[85vh]
    "
    >
      <div className="p-6">

        {/* Header */}

        <div className="flex justify-between items-start">

          <div className="flex gap-4">

            <div className="w-14 h-14 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center text-lg font-semibold">
              {getInitials(feedback.name)}
            </div>

            <div>

              <h2 className="text-xl font-semibold text-gray-900">
                {feedback.name}
              </h2>

              <p className="text-sm text-gray-500 mt-1">
                {feedback.location.flag}{" "}
                {feedback.location.formatted}
              </p>

              <p className="text-sm text-gray-500">
                {feedback.age} years old
              </p>

            </div>

          </div>

          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-700"
          >
            ✕
          </button>

        </div>

        <div className="mt-6">
          <SentimentBadge
            sentiment={
              feedback.analysis.sentiment
            }
          />
        </div>

        {/* Metrics */}

        <div className="grid grid-cols-3 gap-3 mt-6">

          <MetricCard
            icon="⭐"
            title="Rating"
            value={
              feedback.analysis.rating
                ? `${feedback.analysis.rating}/5`
                : "-"
            }
          />

          <MetricCard
            icon="🎯"
            title="Confidence"
            value={`${Math.round(
              feedback.analysis.confidence *
              100
            )}%`}
          />

          <MetricCard
            icon="😊"
            title="Sentiment"
            value={`${Math.round(
              feedback.analysis
                .sentimentScore *
              100
            )}%`}
          />

        </div>

        {/* Original Feedback */}

        <section className="mt-8">

          <h3 className="font-semibold text-gray-900 mb-3">
            Original Customer Feedback
          </h3>

          <div className="rounded-xl border border-gray-200 bg-gray-50 p-4">

            <p className="leading-7 text-gray-700">
              {feedback.feedback}
            </p>

          </div>

        </section>

        {/* AI Summary */}

        <section className="mt-8">

          <h3 className="font-semibold text-gray-900 mb-3">
            AI Summary
          </h3>

          <div className="rounded-xl border-l-4 border-blue-500 bg-blue-50 p-4">

            <p className="leading-7 text-blue-900">
              {feedback.analysis.summary}
            </p>

          </div>

        </section>

        {/* Testimonial */}

        <section className="mt-8">

          <div className="flex items-center gap-2 mb-3">

            <span className="text-sm font-medium text-green-700">
              ✨ Generated by Auric AI
            </span>

          </div>

          <div className="rounded-xl border-l-4 border-green-500 bg-green-50 p-4">

            <p className="italic leading-7 text-green-900">
              "{feedback.analysis.testimonial}"
            </p>

          </div>

        </section>

        {/* Praised */}

        <section className="mt-8">

          <h3 className="font-semibold text-gray-900 mb-3">
            Praised Features
          </h3>

          <div className="flex flex-wrap gap-2">

            {feedback.analysis.praisedFeatures
              .length ? (
              feedback.analysis.praisedFeatures.map(
                (feature) => (
                  <FeatureChip
                    key={feature}
                    value={feature}
                  />
                )
              )
            ) : (
              <p className="text-gray-500 text-sm">
                No highlighted strengths.
              </p>
            )}

          </div>

        </section>

        {/* Improvement */}

        <section className="mt-8">

          <h3 className="font-semibold text-gray-900 mb-3">
            Improvement Areas
          </h3>

          <div className="flex flex-wrap gap-2">

            {feedback.analysis
              .criticizedFeatures
              .length ? (
              feedback.analysis.criticizedFeatures.map(
                (feature) => (
                  <FeatureChip
                    key={feature}
                    value={feature}
                    positive={false}
                  />
                )
              )
            ) : (
              <div className="rounded-lg bg-green-50 text-green-700 px-4 py-2 text-sm">
                🎉 No major concerns identified.
              </div>
            )}

          </div>

        </section>

        {/* Customer Responses */}

        <section className="mt-8">

          <h3 className="font-semibold text-gray-900 mb-4">
            Customer Responses
          </h3>

          <div className="space-y-5">

            {feedback.responses.map(
              (response, index) => (
                <div
                  key={index}
                  className="border-b border-gray-100 pb-4"
                >
                  <p className="text-sm font-medium text-gray-600">
                    {response.question}
                  </p>

                  {renderResponse(
                    response.answer
                  )}
                </div>
              )
            )}

          </div>

        </section>

        {/* Submission */}

        <section className="mt-8">

          <h3 className="font-semibold text-gray-900 mb-4">
            Submission Details
          </h3>

          <div className="space-y-4 text-sm">

            <div className="flex justify-between">

              <span className="text-gray-500">
                Email
              </span>

              <span className="font-medium text-gray-900">
                {feedback.email}
              </span>

            </div>

            <div className="flex justify-between">

              <span className="text-gray-500">
                Submitted
              </span>

              <span className="font-medium text-gray-900">
                {feedback.receivedFull}
              </span>

            </div>

            <div className="flex justify-between">

              <span className="text-gray-500">
                Status
              </span>

              <span className="font-medium text-gray-900">
                {feedback.processingStatus}
              </span>

            </div>

          </div>

        </section>

      </div>
    </div>
  );
}